### ISSUE TITLE
Better Name?

### ISSUE THREAD

**Issue by evant** [evant/binding-collection-adapter#1]

**Comment by thuytrinh** [comment]
`collection-binder`

**Comment by rpattabi** [comment]
How about "Bubbles"? If you think about it there are similarities with collections and data binding.

- Bubbles are like views, there are plenty of them floating around.
- Some bubbles disappear and the new bubbles come up just like the collection views.
- Bubbles show the world around them, similar to data bounded views.
- Bubbles rise up and disappear, similar to scrolled collection views.

So, what do you think? :--)
