### ISSUE TITLE
DiffObservableList should implement clear/add/addAll

### ISSUE THREAD

**Issue by ndori** [evant/binding-collection-adapter#102]
1. it is stated it is same as ObservableList which you can
2. it is expected to work.
3. clearing a this list make sense, also addAll which gets a collection and not a list like update....

**Comment by evant** [comment]
This is supposed to be an immutable view of the list, so those methods are not supported, much like `Collections.unmodifiableList()`. This would completely break diffing if the collection was modified between a diff.
