### ISSUE TITLE
executePendingBindings throws exception once the adapter has observables.

### ISSUE THREAD

**Issue by dk-tkennedy** [evant/binding-collection-adapter#104]
Fatal Exception: java.lang.IllegalStateException
Cannot change whether this adapter has stable IDs while the adapter has registered observers.

We've noticed this can happen if an activity gets destroyed and then rehydrated. The adapter itself is somehow kept around in this case. 

Will add a pull request with possible fix to this.

**Comment by evant** [comment]
Feel free to re-open this if it's still and issue. A sample project to reproduce would be helpful.
