### ISSUE TITLE
What is BR.item?

### ISSUE THREAD

**Issue by chris84948** [evant/binding-collection-adapter#110]
Hey, this is probably a stupid question, but what is BR.item in you code example?

ItemBinding.of(BR.item, R.layout.item);

I'm moving over from c#, so I'm just struggling with what goes where, etc.

Thanks.

**Comment by evant** [comment]
This would probably be a better question to ask on stackoverflow, but it's the id that's generated by databinding that maps to the field defined in the layout

https://developer.android.com/topic/libraries/data-binding/index.html

For example if you had
```
   <data>
       <variable name="user" type="com.example.User"/>
   </data>
```
you'd pass in `BR.user`

**Comment by chris84948** [comment]
Got it. That makes sense. I'm assuming that's shorthand.

Thanks for taking the time.

**Comment by chris84948** [comment]
So I guess I thought I understood this, but I'm still missing something. In
your specific example, where is BR? What is it? Is it an auto-generated
binding class? I guess I'm missing something?

I know this is not really your problem, but I'd appreciate it.

Thanks.

**Comment by chris84948** [comment]
Sorry, cancel that. I finally figured it out. It's dynamically generated.

Thanks again anyway, I think your lib will definitely make my life easier.
It's been tricky switching from WPF to Android.

**Comment by ersin-ertan** [comment]
Be sure to include `apply plugin: 'kotlin-kapt'` in your apps `build.gradle` otherwise you will run into a `Unresolved reference: BR` when using databindingV2
