### ISSUE TITLE
as 3.0  and gradle 3.0+ error

### ISSUE THREAD

**Issue by hueyoung** [evant/binding-collection-adapter#111]
Error:Execution failed for task ':app:compileAppDebugJavaWithJavac'.
> android.databinding.tool.util.LoggedErrorException: Found data binding errors.
  ****/ data binding error ****msg:Cannot find the setter for attribute 'app:itemView' with parameter type me.tatarka.bindingcollectionadapter.ItemViewSelector<T> on android.support.v7.widget.RecyclerView.
  file:C:\Users\000001523\Documents\expand_business_android\XCJD\app\src\main\res\layout\common_recycler_view.xml
  loc:59:32 - 59:49
  ****\ data binding error ****

**Comment by zongdongdong** [comment]
I have the same error, How did you solve it?

**Comment by Lapinou42** [comment]
I resolved this by using the beta => me.tatarka.bindingcollectionadapter:bindingcollectionadapter:2.0.0-beta2

and gradle 3.1.3.
