### ISSUE TITLE
make sections in recyclerview

### ISSUE THREAD

**Issue by hirenpatel868** [evant/binding-collection-adapter#113]
Section 1
   - Item 1
  -  Item 2
Section 2
  - Item1

how to implement this kind of flow in recyclerview using this lib.i want to add sections as well as section item dynamically ?

**Comment by evant** [comment]
I would flatten the list for your ui so you have something like:

- section 1
- item 1
- item 2
- section 2
- item 1

if you also want sticky headers, there's a few libs out there that you can try that help with that. Unfortunately, nothing first-party
