### ISSUE TITLE
Is possible has a list in list item?

### ISSUE THREAD

**Issue by luna-vulpo** [evant/binding-collection-adapter#116]
Is a way to have list in list. Suppose the app has to display list of items and each item has a type. The type is selected form list? (Types depend on what kind of is item but it's not such important for now)

So there is a class:
```
Ware {

String name;
Kind kind = Kind.CUSTOM; 
String type; //<-- selected form limited list of types depends on value in kind
}
```
The app displays list of items and each item has spinner to select a type.

**Comment by evant** [comment]
You are more likely to get a response for general databinding questions on somewhere like [StackOverflow](https://stackoverflow.com/questions/tagged/android-databinding)
