### ISSUE TITLE
Binding events problem

### ISSUE THREAD

**Issue by moshkit** [evant/binding-collection-adapter#12]
If you try to [bind event](https://developer.android.com/intl/ru/tools/data-binding/guide.html#binding_events) in item you will get NullPointerException while building project.

To repeat this issue you can add         android:onClick="@{item.onClick}" to any view in item.xml
and method 
```java
  public void onClick(View view){
        checked = !checked;
        notifyPropertyChanged(me.tatarka.bindingcollectionadapter.sample.BR.checked);
    }
```
in ItemViewModel.java

**Comment by evant** [comment]
You sure this has to do with this library? I'd be very surpized if it caused compile-time issues.

**Comment by moshkit** [comment]
In my opinion this feature is not necessary. It could be easely replaced by listeners. But some information, that Event binding is not supported will be usefull.

**Comment by evant** [comment]
I'll look into it, but there is no reason this feature shouldn't work.

**Comment by evant** [comment]
I was able to do what you showed above without issue. Feel free to check the sample project which I've updated to do this. Are you sure you are on the latest version of databinding?

**Comment by moshkit** [comment]
It is working now.
