### ISSUE TITLE
Cannot find the setter for attribute 'app:items'

### ISSUE THREAD

**Issue by SmallSmallrui** [evant/binding-collection-adapter#122]
Cannot find the setter for attribute 'app:items' with parameter type android.databinding.ObservableList on android.support.v7.widget.RecyclerView.

**Comment by BadElephant** [comment]
I update my gradle plug-in to 3.1.2,and i got similar problem

**Comment by SmallSmallrui** [comment]
yes ,you are right , thank you

**Comment by ZJL2018** [comment]
same problem after I update my gradle plugin to 3.1+

**Comment by hqglichao** [comment]
same problem

**Comment by hqglichao** [comment]
solution: update gradle plug-in to 3.3.0
