### ISSUE TITLE
Documentation has some holes

### ISSUE THREAD

**Issue by robross0606** [evant/binding-collection-adapter#125]
Does the ViewModel need to have a default constructor?  All the examples seem to point to that, but it isn't explicitly stated.  Nor is it stated that the `viewItems` and `viewBinding` must be public fields.  Is it possible to have non-default constructors or to reference accessors instead of fields for binding?  Maybe this is somewhere buried in Android's binding documentation and I haven't found it yet.

**Comment by evant** [comment]
Note: you are more likely to get a response for general databinding questions on somewhere like [StackOverflow](https://stackoverflow.com/questions/tagged/android-databinding)
