### ISSUE TITLE
Where is me.tatarka.bindingcollectionadapter.sample.databinding.RecyclerViewBinding?

### ISSUE THREAD

**Issue by robross0606** [evant/binding-collection-adapter#126]
Your example app references an import:
```
import me.tatarka.bindingcollectionadapter.sample.databinding.RecyclerViewBinding;
```
However, I cannot find this class anywhere.  Is this supposed to be automatically generated or something?

**Comment by evant** [comment]
That class is generated by databinding. Note: you are more likely to get a response for general databinding questions on somewhere like [StackOverflow](https://stackoverflow.com/questions/tagged/android-databinding)
