### ISSUE TITLE
Errors when using android gradle plugin 3.0+

### ISSUE THREAD

**Issue by henrichhanusovsky8** [evant/binding-collection-adapter#127]
When using these two librariers
compile 'me.tatarka.bindingcollectionadapter:bindingcollectionadapter:1.3.0'
compile 'me.tatarka.bindingcollectionadapter:bindingcollectionadapter-recyclerview:1.3.0'

and android gradle plugin in version 3.0+ i get some errors, i can post them here:

`Found data binding errors.
****/ data binding error ****msg:Cannot find the setter for attribute 'app:itemView' with parameter type me.tatarka.bindingcollectionadapter.ItemView on android.support.v4.view.ViewPager.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\fragment_home.xml
loc:48:28 - 48:49
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:itemView' with parameter type me.tatarka.bindingcollectionadapter.ItemView on android.support.v4.view.ViewPager.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout-land\fragment_home.xml
loc:35:28 - 35:49
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:fragment' with parameter type eu.elcom.e80a.home.keyboards.CategoryKeyboardFragment on eu.elcom.e80a.databinding.FragmentListBinding.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\fragment_products_or_categories_list.xml
loc:50:28 - 50:35
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:adapter' with parameter type me.tatarka.bindingcollectionadapter.factories.BindingRecyclerViewAdapterFactory on android.support.v7.widget.RecyclerView.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\dialog_products_count.xml
loc:50:27 - 50:49
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:adapter' with parameter type me.tatarka.bindingcollectionadapter.factories.BindingRecyclerViewAdapterFactory on android.support.v7.widget.RecyclerView.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\fragment_terminals.xml
loc:34:27 - 34:49
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:itemView' with parameter type me.tatarka.bindingcollectionadapter.ItemViewSelector<eu.elcom.e80a.home.viewModels.OrderItemViewModel> on android.support.v7.widget.RecyclerView.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\item_order.xml
loc:104:32 - 104:50
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:itemView' with parameter type me.tatarka.bindingcollectionadapter.ItemView on android.support.v7.widget.RecyclerView.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\dialog_split_order.xml
loc:37:28 - 37:49
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:adapter' with parameter type me.tatarka.bindingcollectionadapter.factories.BindingRecyclerViewAdapterFactory on android.support.v7.widget.RecyclerView.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\fragment_list.xml
loc:34:27 - 34:49
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:adapter' with parameter type me.tatarka.bindingcollectionadapter.factories.BindingRecyclerViewAdapterFactory on android.support.v7.widget.RecyclerView.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\fragment_printers.xml
loc:35:27 - 35:49
****\ data binding error ****
****/ data binding error ****msg:Cannot find the setter for attribute 'app:itemView' with parameter type me.tatarka.bindingcollectionadapter.ItemView on android.widget.Spinner.
file:C:\apps\elcom\ElcomPOS\app\src\main\res\layout\dialog_edit_order.xml
loc:76:32 - 76:53
****\ data binding error ****`

when using gradle plugin of lower versions, e.g. 2.3.3, everything works fine

any solutions on this issue?

**Comment by evant** [comment]
Please try the latest version `2.2.0` (or one of the betas if you want to use databinding v2).

**Comment by Prusinowsky** [comment]
Unfortunately usage version `2.0.0-beta1` and `2.0.1-beta2` doesn't help.
