### ISSUE TITLE
Handling listeners on the list items

### ISSUE THREAD

**Issue by destil** [evant/binding-collection-adapter#13]
Hi,
thank you for your great library. It works fine, but I'm struggling with how to properly handle listeners on the Views that are inside the list item.

AFAIK it's possible to bind only one variable with the list item layout which contains data (using itemView.setBindingVariable()). That's not nice, because now I need to add listeners and their handling to the data object. I think it that listeners should be separated from data object. So I would ask for an advice or little refactoring which will allow to bind more variables to the list item view.

**Comment by evant** [comment]
Yes this is by design. How would you know how to get additional variables that are not in the list? What we have done is wrap each item in the list in a view model that handles clicks and other presentation stuff.

**Comment by destil** [comment]
Are you talking about ItemViewModel class from the sample app? I have something similar, but it mixes data and logic. My data class needs to have a reference to a DAO object because I'm modifying database when the item is clicked. It feels wrong. Do you have some suggestion? Holding listeners statically in some other class?

**Comment by evant** [comment]
It's really up to you. If you want to centralized things you can pass the screen's view model to the ItemViewModel (or an callback interface or whatever) and have it bubble up the click listener.

**Comment by destil** [comment]
OK, thanks.
