### ISSUE TITLE
Call `setLifecycleOwner` on bindings

### ISSUE THREAD

**Issue by wongcain** [evant/binding-collection-adapter#133]
As noted in another issue this library doesn't currently support LiveData. What is particularly challenging is that `ViewDataBinding` objects that the adapters do not get their `setLifecycleOwner` methods called.

**Comment by evant** [comment]
Got a WIP implementation started https://github.com/evant/binding-collection-adapter/tree/livedata-support

**Comment by wongcain** [comment]
FYI - Today at the Android Developer Summit I was able to speak with several Googlers that work on Architecture Components / Data Binding about this issue. I brought their attention to https://issuetracker.google.com/issues/112929938 and they said they should be able to get it resolved soon.  Fingers-crossed.
