### ISSUE TITLE
Add @Nullable and @NonNull annotations to OnItemBind methods and elsewhere

### ISSUE THREAD

**Issue by wongcain** [evant/binding-collection-adapter#137]
Adding annotations to specify what can and cannot be null will allow proper null-checking in Kotlin.  Right now, for example, we have code like this:
```
OnItemBind<MyItem> { itemBinding, _, item ->
        itemBinding!!.set(BR.item, item!!.layout).bindExtra(BR.vm, this)
```
I am making the assumption that itemBinding cannot be null, but perhaps there might be times when it is... ?   If so, this will crash.

**Comment by evant** [comment]
In this case, `itemBinding` cannot be null. But yeah I'll add annotations.

**Comment by evant** [comment]
https://github.com/evant/binding-collection-adapter/pull/139 Added a `bindingcollectonadapter-ktx` module as well to make item binding a bit nicer. Ex: your example would be:

```kotlin
val binding = itemBindingOf<MyItem> { itemBinding, _, item ->
    itemBinding.set(BR.item, item.layout)
}.bindExtra(BR.vm, this)
```
