### ISSUE TITLE
Gradle plugin

### ISSUE THREAD

**Issue by iamthevoid** [evant/binding-collection-adapter#141]
at first - sorry for my bad english 

Could you please update gradle plugin version from 
'com.android.tools.build:gradle:3.2.0-rc02'
to
'com.android.tools.build:gradle:3.2.0-rc03'

and do it every time when studio gets update if it possible?

Gradle plugin use the same databinding dependency version and it conflict with my project databinding dependency version

**Comment by evant** [comment]
Released 3.0.0 which depends on AGB 3.3.0 so there shouldn't be any compatibility issues moving forward.
