### ISSUE TITLE
Binding-collection-adapter vs Epoxy

### ISSUE THREAD

**Issue by qbait** [evant/binding-collection-adapter#144]
I'm starting new complex project and considering Binding-collection-adapter vs Epoxy. Would be great to have comparison between both libs.

**Comment by evant** [comment]
Haven't used Epoxy so wouldn't know. This library is good if you are fulling buying in to databinding.

**Comment by qbait** [comment]
Thank you for the honest answer @evant. I'm using heavily android databinding, will play with Epoxy then and decide.
