### ISSUE TITLE
bindingcollectionadapter-ktx not on jcenter?

### ISSUE THREAD

**Issue by rpattabi** [evant/binding-collection-adapter#151]
I'm trying to include `bindingcollectionadapter-ktx` like below, but it fails:
`implementation "me.tatarka.bindingcollectionadapter2:bindingcollectionadapter-ktx:3.0.0-beta3"`

Gradle sync error: 
`Failed to resolve: me.tatarka.bindingcollectionadapter2:bindingcollectionadapter-ktx:3.0.0-beta3`

**Comment by evant** [comment]
3.0.0 was released on maven central which should include that artifact. Feel free to re-open if you have any issues with it.
