### ISSUE TITLE
AndroidX issue - cannot find symbol class ?

### ISSUE THREAD

**Issue by drmkraja** [evant/binding-collection-adapter#152]
I'm using the latest 3.0.0-beta3 due to AndroidX. But I get **error: cannot find symbol class AddCrop**
I tried Cleaning, Invalidating cache & Rebuilding. But got stuck with the same error like this [Issue](https://github.com/evant/binding-collection-adapter/issues/131)

Please let me know this is related to this library or databinding Issue...

![farmer](https://i.imgur.com/XI0xiOQ.jpg)

**Comment by pratyesh** [comment]
I'm also getting same issue with it. **cannot find symbol class T** 
Any idea, what could be the reason.

**Comment by evant** [comment]
Couldn't reproduce, assuming it was fixed. Feel free to re-open if you are still having issues.
