### ISSUE TITLE
error: cannot find symbol class T

### ISSUE THREAD

**Issue by Ar4ics** [evant/binding-collection-adapter#153]
using Gradle plugin version 3.5.0-alpha02 gives compilation error on this line
`
me.tatarka.bindingcollectionadapter2.ItemBinding<T> variantsbinding = mVariantsbinding;
`

**Comment by lukesleeman** [comment]
Just as a little bit more info, we seem to be experiencing a very similar issue.  For us things compile fine using the android gradle plugin version `3.5.0` but break when changed to `3.5.1` - I suspect it may be somehow related to this bug:  https://issuetracker.google.com/issues/139738910
