### ISSUE TITLE
Can't make pagination to work

### ISSUE THREAD

**Issue by atlantis210** [evant/binding-collection-adapter#166]
Hi, I've been working with your lib for quite some time and I have to admit : you changed my life :D

I was trying to implement the page library with your lib but I cannot make it to work. The `loadRange` is never called... I thought it was coming from the `DiffUtil.ItemCallback` but even if I make it return false the `loadRange` is never triggered. On your sample it works fine though. I've made a sample if you're interested.

Thanks again for your work !

**Comment by evant** [comment]
Yeah, please share it. I can take a look when I get a chance. In the meantime you should try to narrow down what's different between your sample and ours.

**Comment by atlantis210** [comment]
Yeah I tried to see what was different in my sample and yours, see what version of libraries you used, used a simple object for items as you did... but without success.
Here's the sample : https://github.com/atlantis210/PagingLibrarySample

**Comment by atlantis210** [comment]
I think I found something. I put a breakpoint in `BindingRecyclerViewAdapter.getItemViewType(int position)` and saw that my items were AsyncDiffObservableList whereas yours are AsyncDiffPagedObservableList. After further investigation, it looks like I don't have any reference to any PagedBindingRecyclerViewAdapters, only BindingRecyclerViewAdapters. Therefore it displays items as a list and don't do any diff on the list => `mPagedList.loadAround(index);` is never called. Could you check that quickly please ?

**Comment by evant** [comment]
Hm, I wonder if it's selecting the wrong binding adapter because you are using a `LiveData<PagedList<T>>`

**Comment by evant** [comment]
Hm, I don't see you including the `bindingcollectionadapter-paging` artifact.

```groovy
implementation 'me.tatarka.bindingcollectionadapter2:bindingcollectionadapter-paging:3.1.1'
```

**Comment by atlantis210** [comment]
Damn! This is it ... I though it was included in your recyclerview lib. It is not written on your .md though.
Anyway, thanks !

**Comment by evant** [comment]
That's fair, actually there isn't anything about paging written in the README, I'll add a section.
