### ISSUE TITLE
Support for viewpager2 ?

### ISSUE THREAD

**Issue by ANPez** [evant/binding-collection-adapter#169]
## Feature Request
I'd love to see this library include support androidx's ViewPager2

**Comment by tashuodeni** [comment]
> As a note, I've dirty-copy-pasted your BindingRecyclerViewAdapters into my project, changing RecyclerView to ViewPager2, and seems to work.

How do you implement it? I tried to bind viewpager2, but it didn't seem to work. Can you provide an example?
