### ISSUE TITLE
Databinding rc2 causes crashes when using LayoutManager helpers

### ISSUE THREAD

**Issue by Richie97** [evant/binding-collection-adapter#17]
```java.lang.IllegalStateException: Required DataBindingComponent is null in class FragmentLiveBinding. A BindingAdapter in me.tatarka.bindingcollectionadapter.BindingCollectionAdapters is not static and requires an object to use, retrieved from the DataBindingComponent. If you don't use an inflation method taking a DataBindingComponent, use DataBindingUtil.setDefaultComponent or make all BindingAdapter methods static```

Only change being the bump from rc1 -> rc2

**Comment by Richie97** [comment]
```public FragmentLiveBinding(android.databinding.DataBindingComponent bindingComponent, View root) {
        super(bindingComponent, root, 0);
        final Object[] bindings = mapBindings(bindingComponent, root, 2, sIncludes, sViewsWithIds);
        ensureBindingComponentIsNotNull(me.tatarka.bindingcollectionadapter.BindingCollectionAdapters.class);
        this.mboundView0 = (android.widget.RelativeLayout) bindings[0];
        this.mboundView0.setTag(null);
        this.recycler = (android.support.v7.widget.RecyclerView) bindings[1];
        this.recycler.setTag(null);
        setRootTag(root);
        invalidateAll();
    }```

Looks like ensureBindingComponentIsNotNull is the culprit in the stacktrace.

**Comment by evant** [comment]
I couldn't reproduce. Could you try again with `0.13`? It's built against rc2.

**Comment by Richie97** [comment]
.13 seems to work.
