### ISSUE TITLE
Feature Request : Support for FragmentStatePagerAdapter

### ISSUE THREAD

**Issue by satwinder07** [evant/binding-collection-adapter#175]
Is this a general databinding issue or question? You are more likely to get a
response from somewhere like
[StackOverflow](https://stackoverflow.com/questions/tagged/android-databinding).

## Issue
Please be as detailed as possible and include a (formatted) stacktrace if
relevant. A sample project that reproduce the problem goes a long way!

## Feature Request
Please give an example use-case on why the feature is useful. Keep in mind the
scope of this project is to bind data to RecyclerView/ListView/ViewPager etc,
not to add additional features to those views.

**Comment by evant** [comment]
This has already been discussed https://github.com/evant/binding-collection-adapter/issues/15
