### ISSUE TITLE
show popupwindow in recyclerview and crashed

### ISSUE THREAD

**Issue by RockPhoenix** [evant/binding-collection-adapter#177]
I want to show a popupwindow when user click the item, so I write these code in onBindBinding:
`itemBinding.receiveWarehouse.setOnClickListener(v -> {
          ChoosePopup popup = new ChoosePopup(mContext, itemBinding.receiveWarehouse, list);
          popup.showPop(itemBinding.receiveWarehouse);
  });`
ChoosePopup is a custom PopupWindow, and when app runs, it crashed with error:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void me.tatarka.bindingcollectionadapter2.ItemBinding.onItemBind(int, java.lang.Object)' on a null object reference`

code in viewmodel:
`public RequireGoodsMaterialAdapter adapter = new RequireGoodsMaterialAdapter();
    public ObservableList<Object> materialList = new ObservableArrayList<>();
    public OnItemBind<Object> requireGoodItemBinding = (itemBinding, position, item) -> {       
if (position == 0) {
            itemBinding.set(BR.item, R.layout.header_require_goods_detail);
        } else {
            itemBinding.set(BR.item, R.layout.item_require_good_material);
        }
    };`

I can't find the way to fix this bug.

**Comment by evant** [comment]
Thank you for the report! It looks like your issue is not necessarily with this library, I think you'd be better served asking on a site like stackoverflow where more people would be available to help answer it. If you think it is an actual bug, can you create a sample repo showing the issue?
