### ISSUE TITLE
Allow `ItemBinding` to be null while `List == null`

### ISSUE THREAD

**Issue by jasonsparc** [evant/binding-collection-adapter#179]
Sometimes, you want to perform some initial processing to the list before creating the final `OnItemBind` subclass. However, the library will throw an error if `ItemBinding` is null.

It would really be helpful if `ItemBinding` can be null while the list is still null.

Right now, what we're doing is providing a dummy `ItemBinding`, even though it won't really be used, since we'll swap it out with a different implementation anyway once we have a list.

**Comment by jasonsparc** [comment]
Furthermore, having a bunch of `setup.itemBinding ?? ItemBindingUtils.DUMMY_ITEM_BINDING` seems inelegant. We're also finding it tedious to import something like `ItemBindingUtils.DUMMY_ITEM_BINDING` every time. Therefore, if this proposal gets approved, all that boilerplate code will be gone for good, and we would very, very much thank you for that! 🙏

I know that `BindingCollectionAdapter.getItemBinding()` is marked `@NonNull` but, all implementations of `BindingCollectionAdapter` already throws NPE whenever `getItemBinding()` is called while `itemBinding` is still null. Therefore, I believe there shouldn't be any backwards-incompatible changes.

May I also propose a `BindingCollectionAdapter.hasItemBinding()` method, and then allow `BindingCollectionAdapter.setItemBinding(…)` to accept nulls, so that it could be unset (and allow it to be GC'ed) when the list is unset. Alternatively, rather than allowing nulls to `setItemBinding(…)`, have a `setList(@Nullable List<T> items, boolean releaseItemBinding)` instead – since, having a non-nullable `getItemBinding()` and a nullable `setItemBinding(…)` might cause problems with kotlin (but I'm not sure though if it'll be just okay.)

**Comment by evant** [comment]
> However, the library will throw an error if ItemBinding is null.

Where are you seeing this? In the binding adapters? Just want to make sure I understand where the change should happen.

Any issues with with changing the binding adapters to not set/clear the adapter when ItemBinding is null and not changing the `BindingCollectionAdapter` interface?

Note: you should be able to copy that binding adapter code into your project and modify it if you want to test it out.

**Comment by evant** [comment]
> then allow BindingCollectionAdapter.setItemBinding(…) to accept nulls, so that it could be unset (and allow it to be GC'ed) when the list is unset.

Wouldn't it be better to clear out the whole adapter in that case? (ex: `recyclerview.setAdapter(null)`).

**Comment by jasonsparc** [comment]
> > However, the library will throw an error if ItemBinding is null.
> 
> Where are you seeing this? In the binding adapters (ex: `me.tatarka.bindingcollectionadapter2.BindingCollectionAdapters`)? Just want to make sure I understand where the change should happen.

Yup! It's the various `BindingCollectionAdapters`, `BindingSetupRecyclerViewAdapters`, etc., classes.

> Any issues with with changing the binding adapters to not set/clear the adapter when ItemBinding is null and not change the `BindingCollectionAdapter` interface?

Actually, I don't have any issues with it. It'll be fine to keep it as is just so that there's no breaking changes, but I just thought that it seems inconsistent that the various `@BindingAdapter`-annotated methods accepts a null `ItemBinding` but `BindingCollectionAdapter.setItemBinding(…)` does not.

> > then allow BindingCollectionAdapter.setItemBinding(…) to accept nulls, so that it could be unset (and allow it to be GC'ed) when the list is unset.
> 
> Wouldn't it be better to clear out the whole adapter in that case? (ex: `recyclerview.setAdapter(null)`).

Hmm… Actually, that would be just fine by me, especially with our current project.

But, I'm not sure if there are others (including me in the future) who wouldn't want their adapters nulled (e.g., for when they set an adapter once, during the `RecyclerView`'s creation/inflation, and then wants it to be non-null all the time). On the other hand, we could keep it as is, and then simply wait for someone in the future to report an issue.

**Comment by jasonsparc** [comment]
> Any issues with with changing the binding adapters to not set/clear the adapter when ItemBinding is null and not change the BindingCollectionAdapter interface?

Oh! You meant clearing the adapters when `ItemBinding` is null. I was just looking at the newly committed code.

That… I'm not sure about. Someone might not like that, e.g., in case they subclass the adapters and made it really heavy weight (that freeing it and recreating is something they wouldn't want). Also, I just thought of a scenario where they subclass the binding adapters and kept some kind of canvas and a bitmap with it, say, for some custom animated effects. But, then again… ¯\\_(ツ)_/¯

**Comment by jasonsparc** [comment]
Here's an alternatively (but I'm not sure if it's a brilliant idea 😅)…

Rather than clearing the `ItemBinding`, set it to some default, dummy `ItemBinding`. Perhaps also, expose that dummy `ItemBinding` as a utility, so that people can check for it. That way, we still don't introduce breaking changes, we get to keep the `BindingCollectionAdapter` interface as is, and we don't need to null the adapters.

**Comment by evant** [comment]
I'm hesitant to have a non-null adapter with a null itemBinding because without the itemBinding the adapter is kinda useless. Recyclerview actually tries to restore state when you set the adapter so it makes the assumption that if the adapter exists your data does too and I think it's a good idea to carry that on. For the case of a custom adapter you are responsible for providing the instance so you can hold onto it as long as you want regardless of if itemBinding is null and it's actually set on the recyclerview and whatever.

**Comment by jasonsparc** [comment]
> I'm hesitant to have a non-null adapter with a null itemBinding because without the itemBinding the adapter is kinda useless. Recyclerview actually tries to restore state when you set the adapter so it makes the assumption that if the adapter exists your data does too and I think it's a good idea to carry that on. For the case of a custom adapter you are responsible for providing the instance so you can hold onto it as long as you want regardless of if itemBinding is null and it's actually set on the recyclerview and whatever.

Right, I just thought that setting it null does indeed make sense, since it was the `@BindingAdapter` methods that created them anyway, when the user did not supply their own custom adapter.

But, perhaps we should warn the users in the javadocs and the `README`, that setting a null `ItemBinding` would also null out any set adapter.

Now, how about my idea, about setting setting a dummy `ItemBinding` instead of null? Thoughts? i.e.,
https://github.com/evant/binding-collection-adapter/issues/179#issuecomment-592988378

**Comment by jasonsparc** [comment]
We tried the new PR (#180) and I think it's fine. No one bothered complaining so I would say, I approve it! The only thing that's missing now is a note in the README file about the new behavior.

Thank you so much for the quick response and implementation! I'll be sure to check back for the new release. 🎉
