### ISSUE TITLE
Setting ViewPager in ViewPagerIndicator?

### ISSUE THREAD

**Issue by dkpalmer** [evant/binding-collection-adapter#18]
I have a ViewPager setup and working well with this adapter  However, I haven't found a good solution for setting the view pager in the ViewPagerIndicator I'm using (https://github.com/JakeWharton/ViewPagerIndicator, which has a method setViewPager(ViewPager view)).  I tried setting the viewPager after inflating the binding layout, but that class errors out that there is no adapter set.  I have that adapter defined for the ViewPager in XML as "app:adapter="@{viewModel.itemsFactory}"".  Is there a good way to bind/connect these views?

**Comment by evant** [comment]
You just need to bind before you set it.
```java
binding.setViewModel(viewModel);
binding.executePendingBindings();
vpi.setViewPager(binding.viewPager);
```

**Comment by dkpalmer** [comment]
executePendingBindings!  Perfect, thanks.

**Comment by evant** [comment]
Yeah it's kinda annoying that you have to call that method but it kinda makes sense. It's so databinding can batch multiple variables together before updating the view. They will eventually run on the next draw call, but sometimes you need it earlier.

**Comment by dkpalmer** [comment]
Makes sense.  Yeah, I was trying to push it down the chain, but with your lib I wasn't seeing a great spot for it :).  Thanks again.
