### ISSUE TITLE
java.lang.ClassCastException: com.ethanhua.skeleton.SkeletonAdapter cannot be cast to me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter

### ISSUE THREAD

**Issue by shivangbtech** [evant/binding-collection-adapter#181]
I am trying to use the skeleton loading library(https://github.com/ethanhua/Skeleton) with data binding and for recycleView I am using the collection adapter library(https://github.com/evant/binding-collection-adapter)

Exception:
```
java.lang.ClassCastException: com.ethanhua.skeleton.SkeletonAdapter cannot be cast to me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapter
at me.tatarka.bindingcollectionadapter2.BindingRecyclerViewAdapters.setAdapter(BindingRecyclerViewAdapters.java:19)
at com.coroutinedemo.databinding.FragmentTodoListBindingImpl.executeBindings(FragmentTodoListBindingImpl.java:209)
```

Please help to get rid of it.

Get the [Source code](https://github.com/shivangbtech/ExceptionSample) here.

https://stackoverflow.com/questions/60317723/java-lang-classcastexception-com-ethanhua-skeleton-skeletonadapter-cannot-be-ca?noredirect=1#comment106863579_60317723

**Comment by evant** [comment]
Thank you for the report! It looks like your issue is not necessarily with this library. Good job posting to stackoverflow already where more people would be available to help answer it, you should continue to follow-up there.
