### ISSUE TITLE
How to Update item values without changing the whole List ?

### ISSUE THREAD

**Issue by drmkraja** [evant/binding-collection-adapter#183]
I'm working on a Grid List. Where the textviews are getting updated every 5 secs from API Call...
I need to update only the textviews instead of updating whole list.

For Code - Please take a look at this [GIST](https://gist.github.com/drmkraja/975882b0612be60761489b26bcfc54c6) 

I'm using Observable Fields & List. Do I have to use Diff List Please tell me where I'm going wrong ???

**Comment by evant** [comment]
Thank you for the report! It looks like your issue is not necessarily with this library, I think you'd be better served asking on a site like stackoverflow where more people would be available to help answer it. If you think it is an actual bug, can you create a sample repo showing the issue?

**Comment by drmkraja** [comment]
Can you check this & answer it...
https://stackoverflow.com/questions/60579492/how-to-update-item-values-without-changing-the-whole-list
