### ISSUE TITLE
ListView onItemClickListener not work

### ISSUE THREAD

**Issue by zayo** [evant/binding-collection-adapter#20]
I'll try to explain my app:
I have some Json-> POJO Model with multiple arrays of items implementing parcelable. I'm able to set one of this list to intent data without creating items twice. Data are taken with ViewModel which is created simultaneously with activity. ViewModel creates ViewDataModel(model with observable array list of json models and ItemView property) from parcelable intent data. But i need to navigate forward to another activity when listview item is clicked.

So i would have to propagate Activity to ViewModel -> ViewModelData -> ViewModelDataItem(My json model). Am i only one who seeing this like a bad idea? 

So my idea was to add onItemClickListener in my Activity where i have Bindings for listview, that would be perfect solution. But even if i set listener, it's never called. I don't exactly know why. But set data to my bindings loads the listview items. Probably i miss the concept.

Could you please explain how to properly set OnItemClickListener or do what i want with the most clean solution?

**Comment by evant** [comment]
This library should not effect `onItemClickListener`. A sample project to show what you are trying to do would really help.

**Comment by zayo** [comment]
Sorry for my late response. I thing that there is something deep seated. But unfortunatelly i had to left project for a while. So close this. In future i'll try to found problem and if it will be in this lib i'll report it with solution instead.
