### ISSUE TITLE
AssertJ should be test dependency

### ISSUE THREAD

**Issue by WonderCsabo** [evant/binding-collection-adapter#21]
The [build.gradle](https://github.com/evant/binding-collection-adapter/blob/master/bindingcollectionadapter/build.gradle#L44) of the library defines the AssertJ dependency in compile scope instead of test scope. I guess this is a mistake, because this way AssertJ will end up in users' APKs.

To work around this, i currently exclude AssertJ from the transitive dependencies of this library:

```groovy
compile('me.tatarka:bindingcollectionadapter:0.13') {
    exclude group: "org.assertj"
}
```

**Comment by evant** [comment]
Fixed in `0.14`
