### ISSUE TITLE
Refreshing data and keeping it in the original display position?

### ISSUE THREAD

**Issue by hjzlzh123** [evant/binding-collection-adapter#217]
Hi @evant :

Whether it supports refreshing data and keeping it in the original display position?
When new data arrives, it is processed as "clear" and then "added," resulting in a change in the scrolling position. How can i resolve it.

**Comment by evant** [comment]
This is handled by [diffUtil](https://developer.android.com/reference/androidx/recyclerview/widget/DiffUtil), check out docs to how to implement it correctly.

**Comment by hjzlzh123** [comment]
Oh, thanks, I didn't notice this in the document.
