### ISSUE TITLE
How to set default value for spinner?

### ISSUE THREAD

**Issue by krystianpe** [evant/binding-collection-adapter#24]
I'm struggling with spinner. I have to select default item from the list but I couldn't find proper way to do it. I was also having problems with getting selected item from the list (in viewmodel) but I used view from onClick() to get it from view tree. It's working but again I'm not sure if that is recommended way to deal with. Can you provide some insight on that topic?

Edit: I tried using @BindingAdapter on Spinner to set selection but spinner's adapter is still null when method is executed. 
Edit2: found a workaround for @BindingAdapter Spinner's null adapter by using notifyChange() on ViewModel in fragment's onResume(). Question remains if that's the simplest solution.

**Comment by evant** [comment]
I'm confused what exactly your issue is, can you show some sample code? What's wrong with the methods on spinner to get and set the selected item?

**Comment by evant** [comment]
Closing for lack of information, feel free to reopen if you are still having issues.
