### ISSUE TITLE
Adding takeView and dropView on ItemViewModel

### ISSUE THREAD

**Issue by xdgimf** [evant/binding-collection-adapter#27]
I'm using MVVM architecture in my project, My ViewModel is a subclass of this class:

    public class MvvmViewModel<V extends MvvmView> {

        private V mView;

        public MvvmViewModel() { }

        @NonNull
        public V getView() {
            return mView;
        }
     
        @CallSuper
        public void takeView(V view) {
            mView = view;
        }

        @CallSuper
        public void dropView() {
             mView = null;
        }

    }

In a fragment I do it like this

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        mBinding = DataBindingUtil.inflate(inflater, R.layout.orders_fragment_view, container, false);
        mBinding.setViewModel(mViewModel);
        mViewModel.takeView(this);
        return mBinding.getRoot();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        mViewModel.dropView();
    }

My question is where should I call takeView and dropView?, Right now I call takeView on onBindBinding still not sure where to call dropView.
```
@Override
public void onBindBinding(ViewDataBinding binding, int bindingVariable, @LayoutRes int layoutRes, int position, T item) {
    super.onBindBinding(binding, bindingVariable, layoutRes, position, item);
    // item.takeView(binding.getRoot());
}
```

**Comment by kim-montano** [comment]
I was wondering the same thing. Can anyone clarify?

**Comment by evant** [comment]
I'm not familiar with this pattern. Can you give an example on how you would do this in a normal adapter and why you are having trouble with this library? If I had to guess, I believe recyclerview has some callbacks when an item is recycled.

**Comment by xdgimf** [comment]
Haven't tried this yet on normal adapter.
-> If I had to guess, I believe recyclerview has some callbacks when an item is recycled.
hmm seems like I found what i'm looking for
````
    @Override
    public void onViewAttachedToWindow(ViewHolder holder) {
        super.onViewAttachedToWindow(holder);
        Logger.i("");
    }

    @Override
    public void onViewDetachedFromWindow(ViewHolder holder) {
        super.onViewDetachedFromWindow(holder);
        Logger.i("");
    }
````
