### ISSUE TITLE
notifyDataSetChanged not releasing old binding

### ISSUE THREAD

**Issue by xdgimf** [evant/binding-collection-adapter#28]
When calling recyclerView adapter notifyDataSetChanged seems like the old bindings are not released. I noticed this when I put a breakpoint on executeBinding and its called multiple times even though I'm only updating 1 property.

I created a sample project for this https://github.com/xdgimf/SampleBindingCollectionAdapter

ItemViewModel
````
public class ItemViewModel {

    public final ObservableBoolean selected = new ObservableBoolean();

    public final ObservableField<String> text = new ObservableField<>();

    public final View.OnClickListener clickListener = new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            if (selected.get()) {
                selected.set(false);
            } else {
                selected.set(true);
            }
        }
    };

    public ItemViewModel(String text) {
        this.text.set(text);
    }

}
````

1. Click on first item = call selected.set(true) then executeBinding  is called once
2. Click refresh = call recycler view adapter notifyDataSetChanged and first item is still selected
3. Click first item again = call selected.set(false) then executeBinding is called twice 

Also let say if you refresh 5 times, then executeBinding is called 5 times.

Update:
I found out that the problem was caused by using ObservableField, everytime the adapter creates a binding, ObservableField adds the binding to its callbacks, this callbacks is called everytime the property is changed.

**Comment by evant** [comment]
I know you closed this but it _sounds_ like a bug to me. However, I'm having trouble reproducing in your linked sample project. I put a breakpoint on `ItemBinding#executeBindings()` and followed your steps above and am only seeing it called once. Am I misunderstanding the issue?

**Comment by xdgimf** [comment]
Try clicking refresh many times rapidly like 10 times (enable the breakpoint) then select the first item
