### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by KrzysztofWrobel** [evant/binding-collection-adapter#29]
Is:
>compile 'me.tatarka.bindingcollectionadaper:bindingcollectionadapter:1.0.0'
>compile 'me.tatarka.bindingcollectionadaper:bindingcollectionadapter-recyclerview:1.0.0'

should be:

>compile 'me.tatarka.bindingcollectionadapter:bindingcollectionadapter:1.0.0'
>compile 'me.tatarka.bindingcollectionadapter:bindingcollectionadapter-recyclerview:1.0.0'

Copy-paste caught me off guard : )

**Comment by evant** [comment]
Thanks! Fixed.
