### ISSUE TITLE
Expanding Fragments

### ISSUE THREAD

**Issue by Queuecumber** [evant/binding-collection-adapter#36]
I am trying to data bind to a collection of elements where different typed elements can have a different fragment to represent them. To do this, I created a new `BindngRecyclerViewAdapter` but I am having the issue that when expand fragments during binding, they appear on top of one another. Here is my `onBindBinding` override

```
@Override
    public void onBindBinding(ViewDataBinding binding, int bindingVariable, @LayoutRes int layoutId, int position, T item) {
        super.onBindBinding(binding, bindingVariable, layoutId, position, item);

        Class fragmentClass = MainActivity.modelToFragment.get(item.getClass());
        if(fragmentClass != null) {
            try {
                Method ninst = fragmentClass.getMethod("newInstance", item.getClass());
                DialogFragment display = (DialogFragment)ninst.invoke(null, item);

                FragmentTransaction ft = ((AppCompatActivity)binding.getRoot().getContext()).getSupportFragmentManager().beginTransaction();
                ft.add(binding.getRoot().getId(), display);
                ft.commit();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
```

When my app is running, I can see new cards being push into the view for each item in my `ObservableArrayList`, but the fragment is always expanded into the first card. Am I going about this wrong or is there some issue with the `ViewDataBinding` that I am being passed?

**Comment by evant** [comment]
1) Using fragments in a recyclerview is a really bad idea. The lifecycle of fragments and the lifecycle of item views do not match at all.
2) You are adding a new fragment on bind but not removing the existing one on that view. Remember that views are recycled so you may get a on bind call several times with the same view.
3) Fragments add themselves to the layout hierarchy by doing a `findViewById()` with their given id and then attaching themselves to the returned view. Unfortunately, all your item views have the same id, so it's always just going to find the first one that is visible.

**Comment by Queuecumber** [comment]
This is what I assumed was the problem. Is there any reasonable way to do
what I want? The huge advantage to this is that I can reuse the same UI in
several places in my app including in confirmation dialogs etc

**Comment by evant** [comment]
If you just want reuse a custom view should get you that. You might want to ask for help in other avenues. Your issue doesn't really have to do with this library. You'd run into the same issues when using just a plain old adapter.

**Comment by Queuecumber** [comment]
Custom view would probably work fine. I wanted to see what you recommended since your library is, according to google, the de-facto way to bind collections (why android doesn't include this functionality by default is beyond me).
