### ISSUE TITLE
Items in RecyclerView not properly recycled

### ISSUE THREAD

**Issue by Skrawlr** [evant/binding-collection-adapter#37]
Hi and first of all thx for this very useful library. That being said, I think there's a bug when using it with a RecyclerView.

So, the thing is, I have a RecyclerView whose items are forms made of a bunch of EditTexts. Those forms are actually linked to a ViewModel so when I write something in one of the EditTexts, it updates my viewModels accordingly thx to DataBinding.
This seems to work, my ViewModel instances are correctly being updated so there isn't the problem.

Let's now say I have 3 items in my RecyclerView, their first EditText being initialized with incremented string + numbers on the go (so "item 1", "item 2", "item 3"). Scrolling from top to bottom isn't a problem but when scrolling back up, the EditText's content get all messed up.
My attempt at an explanation of this would be that the items that are being recycled when  disappearing from the screen are not being "debinded" from their ViewModel. Therefore, when scrolling, the values of the first items are being updated because they are becoming the last items (which are being initialized on the go).

Scenario:

- Initializing first item, (EditText = "item 1", updating the ViewModel),
- Scrolling down,
- Recycling first item, (seemingly not "debinding" it's viewmodel),
- Reusing first item as third item,
- Initializing third item (EditText = "item 3") still binded to the first item's ViewModel (since the third item IS the first item because that's how a RecyclerView works),
- Updating third item's ViewModel which is still binded to the first item,
- Scrolling back up to the first item,
- "item 3" is now written in the first item's editText because its viewModel said so.

Hope it helps, if you need a code example or something, just ask, I'll see what I can do.

**Comment by evant** [comment]
Yes a code example should help a lot here.

**Comment by Skrawlr** [comment]
There : https://github.com/Skrawlr/BindingCollectionAdapterExampleGitHub

You can try it for yourself, it's basically just an activity with a recyclerview having this problem.

**Comment by evant** [comment]
Figured it out: It looks like the databinding lib doesn't have a specific `@BindingAdapter` override for `addTextChangedListener`. Therefore it's just delegating to the existing setter which adds one but _does not remove_ the existing one. One way to solve this issue is to use the one of `android:beforeTextChanged`, `android:onTextChanged`, `android:afterTextChanged` instead (See `android.databinding.adapters.TextViewBindingAdapter.java`) You could also try the two-way binding support added in the latest version https://halfthought.wordpress.com/2016/03/23/2-way-data-binding-on-android/

**Comment by Skrawlr** [comment]
Okay, thanx a lot!

**Comment by ANPez** [comment]
I'm having this issue when migrating a view using ObservableArrayList to a MutableLiveData<List>. With ObservableList everything works and the views get recycled without a problem. With LiveData, views are not recycled and the memory usage raises a lot (as my cells show images).

Not using any two way binding or anything else "weird". Just a MutableLiveData<List<BaseObservable>>
