### ISSUE TITLE
ItemViewSelector selecting wrong layout

### ISSUE THREAD

**Issue by elmateo487** [evant/binding-collection-adapter#38]
Ok so here is how I have this setup. And with this setup, if you scroll the list view the items changes between the different layouts.

```
public class TimelineVM {
    public final ObservableList<NotificationAbstract> items = new ObservableArrayList<>();
    public final ItemViewSelector<NotificationAbstract> itemView = new BaseItemViewSelector<NotificationAbstract>() {
        @Override
        public void select(ItemView itemView, int position, NotificationAbstract item) {
            if (item instanceof ChatNotification) {
                itemView.set(BR.item, R.layout.notification_chat_layout);
            } else if (item instanceof TrackNotification) {
                itemView.set(BR.item, R.layout.notification_track_layout);
            } else if (item instanceof StatusNotification) {
                itemView.set(BR.item, R.layout.notification_status_layout);
            }
        }
    };

    private View mRootView;

    public void setRootView(View view) {
        mRootView = view;
    }
}
```

Then I am binding the fragment to the VM

```
public class TimelineFragment extends Fragment {

    private TimelineVM mTimelineListVM;
    private TimelineListBinding mBinding;

    // newInstance constructor for creating fragment with arguments
    public static TimelineFragment newInstance() {
        TimelineFragment fragmentFirst = new TimelineFragment();
        return fragmentFirst;
    }

    // Store instance variables based on arguments passed
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRetainInstance(true);
        mTimelineListVM = FslNotificationManager.getTimelineVM();
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        mTimelineListVM.setRootView(getView());
    }

    // Inflate the view for the fragment based on layout XML
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        mBinding = TimelineListBinding.inflate(inflater, container, false);

        mBinding.setTimelineVM(mTimelineListVM);
        mBinding.executePendingBindings();
        return mBinding.getRoot();
    }

    @Override
    public void onStart() {
        super.onStart();
    }
}
```

The layouts are each bound like this

```
    <data>

        <variable
            name="item"
            type="redacted.NotificationAbstract" />
    </data>
```

Then with that bound static list, I will do a
`                mTimelineVM.items.add(notification);
`

**Comment by evant** [comment]
Check to see if you are missing a type in your insanceof chain. Also if you are using `setRetainInstance(true)` you need to null out your `mBinding` in `onDestroyView()` to prevent leaks.

**Comment by elmateo487** [comment]
Yeah, not missing any types in the chain. It is like it is returning the wrong position.  When I log out the position when adding the first item I get

0
0
0

then on adding the second

1
1
1
0
0
0

then on the third

2
2
2
1
1
1
0
0
0

and so on.

When scrolling around I get the following

1
1
1
0
0
0
5
5
5
6
6
6
7
7
7
2
2
2
1
1
1
0
0
0

**Comment by elmateo487** [comment]
Ok..... so all I changed was

        @Override
        public int viewTypeCount() {
            return 3;
        }

and it is working. But thought that was only for a bindinglistviewadapter and this is collection adapter.

**Comment by evant** [comment]
Ah that would do it. You need that method when using a ListView, but not a RecyclerView or ViewPager. I should make the documentation more clear on that.

**Comment by elmateo487** [comment]
Phew, Glad it is working. I am loving it thus far. 

THANKS

**Comment by evant** [comment]
Updated the README I hope it's enough. I guess I could try to make it fail fast if the viewTypeCount isn't what it expects but I'm not sure the complexity is worth it.
