### ISSUE TITLE
app:itemDropdownView ?

### ISSUE THREAD

**Issue by curioustechizen** [evant/binding-collection-adapter#4]
For a `Spinner` etc, would it make more sense to replace  `itemView.setLayoutRes(BindingListViewAdapter.DROP_DOWN_LAYOUT, R.layout.item_dropdown);` with just binding directly in the XML?

```xml
<Spinner
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      app:items="@{viewModel.items}"
      app:itemView="@{viewModel.itemView}"
      app:itemDropdownView="@{viewModel.itemDropdownView}"/>
```

**Comment by evant** [comment]
Upside: Simplifies ItemView, maybe a bit more clear
Downside: n more BindingAdapters
