### ISSUE TITLE
Add support for itemview multi binding variable.

### ISSUE THREAD

**Issue by lowwor** [evant/binding-collection-adapter#40]
Hello, I am trying to use this library to bind something like the following
（Similar code can be found in the [https://github.com/googlesamples/android-architecture/tree/todo-databinding](https://github.com/googlesamples/android-architecture/tree/todo-databinding) ）
R.layout.task_item

```
<layout xmlns:android="http://schemas.android.com/apk/res/android">
    <data>
        <variable
            name="task"
            type="com.example.android.architecture.blueprints.todoapp.data.Task" />
        <variable
            name="actionHandler"
            type="com.example.android.architecture.blueprints.todoapp.tasks.TasksItemActionHandler" />
    </data>
   ...
</layout>
```

But it seems that itemview only accept single binding variable and I have no way to bind the TasksItemActionHandler  in the adapter. 
It will be great that itemview can accept multi binding variables. What do you think ? Thank you.

**Comment by evant** [comment]
It gets the items to bind from the list you provide. How would you suggest to be able to provide additional variables? You can always provide both by wrapping your items and binding that.
```java
public class TaskViewModel {
   public final Task task;
   public final TasksItemActionHandler actionHandler;
   ....
}
```

**Comment by lowwor** [comment]
What I want to achieve is something like following.
```
public class MyRecyclerViewAdapter<T> extends BindingRecyclerViewAdapter<T> {
   private Presenter presenter;
    public MyRecyclerViewAdapter(@NonNull ItemViewArg<T> arg,Presenter presenter) {
      super(arg);
     this.presenter = presenter;
    }

    @Override
    public ViewDataBinding onCreateBinding(LayoutInflater inflater, @LayoutRes int layoutId, ViewGroup viewGroup) {
        ViewDataBinding binding = super.onCreateBinding(inflater, layoutId, viewGroup);
        Log.d(TAG, "created binding: " + binding);
        return binding;
    }

    @Override
    public void onBindBinding(ViewDataBinding binding, int bindingVariable, @LayoutRes int layoutId, int position, T item) {
        super.onBindBinding(binding, bindingVariable, layoutId, position, item);
        binding.setVariable(BR.actionHandler,new TasksItemActionHandler(presenter));
        Log.d(TAG, "bound binding: " + binding + " at position: " + position);
    }
}
```
So that I can just directly bind the action to the actionHandler in the xml. Viewmodel doesn't need to know about the actionHandler and doesn't have to have a reference to the presenter.
    ```
   <CheckBox
            android:id="@+id/complete"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:checked="@{task.isCompleted}"
            android:onCheckedChanged="@{(cb, isChecked) -> actionHandler.completeChanged(task, isChecked)}" />
```

**Comment by evant** [comment]
Ok I understand that, I'm just trying to think on how to implement it. It would be cool to do like `<include/>` does and pass through any extra bindings. Unfortunately, I don't think that's possible to define a similar behavior. I could add a way to do it in code with an extra param. Something like
```java
public SpareArray extraBindings = new SparseArray();
extraBindings.put(BR.actionHandler, new TasksItemActionHandler(presenter);
```
```xml
<RecyclerView
  app:extraBindings="@{extraBindings} />
```

**Comment by lowwor** [comment]
Nice, thanks. Looking forward to it.

**Comment by evant** [comment]
This is going to be supported in `2.0`. It is currently implemented in https://github.com/evant/binding-collection-adapter/tree/beta

**Comment by lowwor** [comment]
Great! Do we have a snapshot dependency or do I have to download the whole project as a dependency ?

**Comment by evant** [comment]
Nothing is uploaded yet, will get around to it soon.

**Comment by evant** [comment]
Uploaded now as `2.0.0-beta1`

**Comment by lowwor** [comment]
Thanks for the beta version.
But when I'm trying to migrate to 2.0.0, it seems that there is something wrong with the returning type of bindExtra as shown in the pic below.
![screencapture at sat aug 6 23 08 14 cst 2016](https://cloud.githubusercontent.com/assets/5444033/17457451/4af99e58-5c2b-11e6-8d52-7cae2ab221c8.png)
Can you track with that? Thanks!

**Comment by Dev-iL** [comment]
I'm having the same problem as @lowwor .

The return type of `ItemBinding.of()` is `<T> ItemBinding<T>`, whereas for `ItemBinding.bindExtra` it's ` ItemBinding<T>`.

(P.S. thanks for the new version!)

**Comment by evant** [comment]
This seems like a limitation of java's type inference. It should work if you do something like
```java
ItemBinding.<ViewModel>of(BR.var, R.layout.item).bindExtra(BR.var2, value);
```
@Dev-iL your solution is correctly marked as a warning because if you do it that way the generic might not match what it should be without warning. It's not a problem in this example, but it is if you use the onItemBind callback version.

```java
// Item in Integer
ItemBinding<Integer> binding = ItemBinding.of(new OnItemBind<String>() {
    @Override
    public void onItemBind(ItemBinding itemBinding, int position, String item) {
       // Item is string
    }
}).bindExtra(BR.var, value);
```
This isn't ideal, but I'm not sure there is a more ergonomic solution to it. I'm all ears if someone can think of something.

**Comment by Dev-iL** [comment]
@evant Thanks for your comment. I've followed your 1<sup>st</sup> suggestion in my code.
BTW, feel free to use the other commit I pushed (...along with my suggested fix) - it includes updates for dependency versions (https://github.com/Dev-iL/binding-collection-adapter/commit/89ec7578970f99c3cd77ea32e58419e90d47caee) .. I've updated everything except for one of the `assertj`s that somehow slipped through :)

**Comment by evant** [comment]
Added in 2.0.0
