### ISSUE TITLE
How to bind an adapter to an individual cell

### ISSUE THREAD

**Issue by zachlucas** [evant/binding-collection-adapter#41]
For my individual `item.xml`, I need direct programmatic manipulation.  For manipulation of the ListView, I'm using a `BindingListViewAdapter`, per the introduction to this library.  I need direct access to the child views in my individual cells, is that possible?  I've tried attaching an activity like normal, but `onCreate` never fires for any of them.

**Comment by evant** [comment]
Yeah subclassing `BindingListViewAdapter` is the correct thing. You should be able to cast `ViewDataBinding` to `ItemBinding` and access your child views that way. Either in `onCreateBinding` or `onBindBinding` depending on when you need to modify it.

**Comment by zachlucas** [comment]
Thank you, makes sense.  Is there a way to properly use the `getView` method in my `BindingListViewAdapter` subclass?  I find myself needing a context in the subclass to manipulate parts of the view, but I can't find a way to retrieve the `context`.

**Comment by evant** [comment]
You have a couple of options. If you already have a reference to the view you can do `view.getContext()` or even `binding.getRoot().getContext()` for your root view. Alternatively you can pass a context into the constructor of the `BindingListViewAdapter` and use `BindingListViewAdapterFactory` to construct it.

**Comment by zachlucas** [comment]
Thank you so much!! A+ A+ A+ A+
