### ISSUE TITLE
Weird behavior with onItemClick

### ISSUE THREAD

**Issue by Golbark** [evant/binding-collection-adapter#44]
Hello,

Here is the situation: I have a ListView configured with binding collection adapter. The items are filled in correctly. However, when I try to operate on the view returned by the onItemClick event, I observe strange behavior. Here is the code of the onItemClick method:

```
public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        boolean isSelected = //is this position selected already ?
        if(isSelected) {
            view.setBackgroundColor(Color.TRANSPARENT);
        } else {
            view.setBackgroundColor(ContextCompat.getColor(getActivity(), R.color.selected));
        }
    }
```

This method works absolutely fine when the list is short enough and you don't have to scroll down. But as soon as you start scrolling, other views than the ones clicked will be colored. Any idea on how to fix this issue ?

Thanks

**Comment by evant** [comment]
On item click is only called when an item is clicked. Since the view is recycled it will continue to have that background in other places. You need to set the color in on bind. An easy way to do this is to databind the background and call notifyDataSetChanged in the onclick.

**Comment by Golbark** [comment]
Ok thanks it works better indeed ! I had to do some add/remove tricks otherwise only calling notifyDataSetChanged did not work.
