### ISSUE TITLE
Enhancement suggestion: allow usage of custom ViewHolder implementation

### ISSUE THREAD

**Issue by BobOtike** [evant/binding-collection-adapter#48]
While using your library in combination with `RecyclerView` I came across this article as I was implementing my own multi-selection mechanism: [https://www.bignerdranch.com/blog/recyclerview-part-2-choice-modes/](url)

They suggest subclassing `RecyclerView.ViewHolder` to give the indication of the selected state a more polished feel. Using the library, there is unfortunately no way to do that as of now. 

I am also using this library in my project: [https://github.com/mikepenz/MaterialDrawer](url)

The items in the drawer are also being displayed in a `RecyclerView`. To give the user the possibility to fully customize or create an own implementation of an item inside the drawer, they give you the following pattern to work with, where `BaseViewHolder` and `ViewHolderFactory` are classes from the library:

    public ViewHolderFactory<ViewHolder> getFactory() {
        return new ItemFactory();
    }

    public static class ItemFactory implements ViewHolderFactory<ViewHolder> {

        @Override
        public ViewHolder create(View v) {
            return new ViewHolder(v);
        }
    }

    public static class ViewHolder extends BaseViewHolder {
		// custom variables here
	
        public ViewHolder(View view) {
            super(view);
			// custom code here
        }
    }

If the `BindingRecyclerViewAdapter` would provide some methods along those lines to override instead of directly instantiating the standard `RecyclerView.ViewHolder` directly, it would be easy to use a custom `ViewHolder`. 

I would love to hear back from you and get your thoughts on the matter.

**Comment by evant** [comment]
Hm, I don't think this is necessary. You can already subclass the adapter and get access to the viewholder. If you need to store info per item you could do that with a simple map. You could also store something like the selected state directly on the items in the collection.

**Comment by sevar83** [comment]
There are 3rd party libraries like https://github.com/bignerdranch/recyclerview-multiselect that requires to use their base viewholder. Even if I subclass `BindingRecyclerViewAdapter` I can't change its viewholder class.

**Comment by evant** [comment]
Hm, ok. I'll think of something, it will probably still require subclassing `BindingRecyclerViewAdapter`
