### ISSUE TITLE
**.databinding no exist

### ISSUE THREAD

**Issue by lockingroad** [evant/binding-collection-adapter#53]
In my demo.  all databinding  can import automatically. but when it ruuning
Error msg show that :
Error:(10, 44) 错误: 程序包com.xhyy.lxr.listviewdb1.databinding不存在(“不存在”means not exist)

**Comment by josefkorbel** [comment]
Make sure you have your <data> in your xml layout, *.binding packages are generated automatically AFTER you create your XML binding.
