### ISSUE TITLE
Could not find adapters.jar (com.android.databinding:adapters:1.1)

### ISSUE THREAD

**Issue by alex4o** [evant/binding-collection-adapter#67]
> Error:Gradle: A problem occurred configuring project ':app'.
>  > Could not find adapters.jar (com.android.databinding:adapters:1.1).
>  Searched in the following locations:
>      https://jcenter.bintray.com/com/android/databinding/adapters/1.1/adapters-1.1.jar

I'am sure that I'am with the latest version of android studio. The error ocures when I add the library in my dependencies like this

> ```
> compile 'me.tatarka.bindingcollectionadapter:bindingcollectionadapter:2.0.0-beta2'  
> ```

I use the Kotlin plugin, but I don't think that is the problem.

**Comment by evant** [comment]
Have you tried updating with the Android sdk manager?
