### ISSUE TITLE
Handling item selection 2-way binding on Spinners

### ISSUE THREAD

**Issue by Trellian** [evant/binding-collection-adapter#68]
Hi, 

Is there a way to implement something like "bind:selection" on an AppCompatSpinner to achieve 2-way binding? I have tried several routes involving BindingAdapters and InverseBindingAdapters, but I can't get anything to work.

Thanks,
Adrian

**Comment by janbina** [comment]
Hi, it should be possible with something like this: `android:selectedItemPosition="@={viewModel.selectedItem}"`, where `selectedItem` is `ObservableInt` inside you viewModel/whatever. 
I'm using this in my app.
