### ISSUE TITLE
RecyclerView binding item type count

### ISSUE THREAD

**Issue by ghost** [evant/binding-collection-adapter#69]
I think that your recycler view adapter should contains the "itemTypeCount" as well, because when list of items is empty the static item doesn't appear. When list of items already have some elements the static item take place of first list's item.

if getItemCount() return 0 recycler view won't call onCreateViewHolder() etc.

``` java
    @Override
    public int getItemCount() {
        return items == null ? 0 : items.size();
    }
```

so developer should bind its item type count or something like that

``` java
    @Override
    public int getItemCount() {
        return items == null ? itemTypeCount : items.size() + itemTypeCount;
    }
```

**Comment by evant** [comment]
"static item doesn't appear" what do you mean by this? There isn't a concept of a "static item" in the lib, it shows exactly what's in your collection. `itemTypeCount` represents the number of different kinds of layouts you may have, there is no relation between it and item count.

**Comment by SlawomirOnyszko** [comment]
As a static item I understand: a header or a different kind of layout. It's possible to add any element to the list but the adapter that you have written does not include the quantity of the additional elements.. The RecyclerView adapter must know the quantity of these additional view types. RecyclerView relays on the number of the items and the onCreateViewHolder won't work if the method getItemCount will return 0.

**Comment by evant** [comment]
The sample now includes an example with a header and footer. Should be pretty clear how you should implment this, but let me know if it isn't.
