### ISSUE TITLE
Data bidning error

### ISSUE THREAD

**Issue by moshkit** [evant/binding-collection-adapter#7]
****/ data binding error ****msg:Cannot find the setter for attribute 'app:items' with parameter type android.databinding.ObservableList<'java.lang.Object'>.

In case of using multiple views adapter
Started  at 0.11 in 0.10 works fine

**Comment by evant** [comment]
Can you post what view this is for and all the things you are binding to it?

**Comment by moshkit** [comment]
app:items="@{MyModel.items}

public ObservableList<Object> getItems()

**Comment by evant** [comment]
That can't be right, at the very least you need the items and the itemView. Also, what's the _view_ you are trying to use this in? LisetView? RecyclerView? ViewPager?

**Comment by moshkit** [comment]
Layout 
           android:layout_weight="1"
            app:layoutManager="@{LayoutManagers.linear()}"
            app:items="@{model.promoItems}"
            app:itemView="@{model.itemSelector}"

Code

        return new BaseItemViewSelector() {
            @Override
            public void select(ItemView itemView, int i, Object o) {
                itemView.set(BR.model, i == 0 ? R.layout.item_channel_online : R.layout.item_channel);
            }

            @Override
            public int viewTypeCount() {
                return 2;
            }
        };

**Comment by moshkit** [comment]
It could be a problem with @BindingConversion annotations. 
Class BindingCollectionAdapters

old        <T> void setAdapter(RecyclerView recyclerView, ItemView itemView, Collection<T> items) {
new -   <T> void setAdapter(RecyclerView recyclerView, ItemViewArg<T> arg, Collection<T> items) {

Old ItemView shpuld be convertes to ItemViewArg<T> using 
    @BindingConversion
    public static ItemViewArg toItemViewArg(ItemViewSelector<?> selector) {
        return ItemViewArg.of(selector);
    }

May be there is some problem here

**Comment by evant** [comment]
This appares to be a limitation in generics when using a `@BindingConversion`. I have submitted it an [issue](https://code.google.com/p/android/issues/detail?id=183651). In the mean time, you can just stick to 0.10 or work around it by supplying your own `@BindingConversion` with the explicit type.

For your example with a raw type:
```
@BindingConversion
public static ItemViewArg toItemViewArg(ItemViewSelector selector) {
    return ItemViewArg.of(selector);
}
```
If you need generics (yes you have to create one for each type you use):
```
@BindingConversion
public static ItemViewArg toItemViewArg(ItemViewSelector<String> selector) {
    return ItemViewArg.of(selector);
}
```

**Comment by moshkit** [comment]
Workaround with BindingConversions does not work
In my case I use BaseModel class for all models. and I created
```java
    @BindingConversion
    public static ItemViewArg<'BaseModel'> toItemViewArg(ItemViewSelector<'BaseModel'> selector) {
        return ItemViewArg.of(selector);
    }
```

**Comment by evant** [comment]
Don't put the type param on ItemViewArg. Though I plan to release an update that works around this soon.

**Comment by moshkit** [comment]
Yeh. i found it.
The problem was in my conversion to:
Wrong code - 
```java
    @BindingConversion
    public static ItemView toItemViewArg(int layoutId) {
        return ItemView.of(BR.model, layoutId);
    }
```

OK code -
```java 
    @BindingConversion
    public static ItemViewArg toItemViewArg(ItemViewSelector<'BaseItemModel'> selector) {
        return ItemViewArg.of(selector);
    }

    @BindingConversion
    public static ItemViewArg toItemViewArg(int layoutId) {
        ItemView view = ItemView.of(BR.model, layoutId);
        return ItemViewArg.of(view);
    }
```
I use ItemViewSelector<BaseItemModel> because I change types of my items to ObservableList<'BaseItemModel'> mItems. <'Object'> is not very good )))

**Comment by evant** [comment]
You should no longer need any work-arounds in `0.12`. I'm closing this and opening https://github.com/evant/binding-collection-adapter/issues/10 to track the android databinding issue.

**Comment by bj0** [comment]
Does this work with ListView?  I tried the simplest case ("Usage" in the readme), but with a custom Item class instead of a String, and I get this binding error.

**Comment by evant** [comment]
The [sample app](https://github.com/evant/binding-collection-adapter/blob/master/app/src/main/res/layout/list_view.xml) has a listview example, can you help pinpoint how what you are doing differs?

**Comment by bj0** [comment]
I was just reading through the sample app's source and from what I can tell the only difference is that I don't set ```app:itemIds```.  I'll pull it down and try to compile it.

**Comment by bj0** [comment]
So, after a couple hours changing just about everything in my gradle files, I realized I was using ```app:itemViewBinder``` instead of ```app:itemView```.  Oops!  Thanks for the useful library!
