### ISSUE TITLE
Usage of your lib in a generator

### ISSUE THREAD

**Issue by joxad** [evant/binding-collection-adapter#71]
@evant 
Thanks a lot for your lib, I use it a lot in my personal / pro projects.
I created two libs around the Databinding/MVVM way of thinking.

The first one is a wrapper around the databinding, in order to have activity, activityvm/ fragment, fragmentVM, model/modelVM. 
https://github.com/joxad/easydatabinding
=> for this one, I works well but I am not sure 100% this is the best way to do it.

The second one is a generator in order to create faster activity/fragment , layout and vms : 
https://github.com/joxad/generator-android-template

I am quite happy with this way of working, but I want to go further, in order to limit the most the manual part.

I have in the idea to then allow to generate activity / fragment with more subsidiary questions like : 
- does your activity contain a list ? yes/no
- which kind of list ? -vp -rv ...

And then generate XML and JAVA code using your lib.

For now, my two libs doesn't use directly you lib, I would like to know if you are ok if I use it more in the generator in the futur.

**Comment by evant** [comment]
Go for it!
