### ISSUE TITLE
Scroll position not kept on screen rotation

### ISSUE THREAD

**Issue by vtarantik** [evant/binding-collection-adapter#77]
In version 2.0.1, using default adapter, the scroll position is not kept on device rotation.

**Comment by evant** [comment]
Can you provide a sample that reproduces the issue? It works fine in the sample app.

**Comment by vtarantik** [comment]
Sure thing,
I declare the RecyclerView like this:
`			<android.support.v7.widget.RecyclerView
				android:id="@+id/movie_list"
				android:layout_width="match_parent"
				android:layout_height="match_parent"
				app:layoutManager="@{LayoutManagers.grid(2)}"
				app:items="@{viewModel.movies}"
				app:itemBinding="@{viewModel.itemBinding}">`

Then in my viewmodel, I simply do this:

`public final ObservableArrayList<Movie> movies = new ObservableArrayList<>();

public final ItemBinding<Movie> itemBinding = ItemBinding.of(BR.item, R.layout.movie_tile);`

**Comment by evant** [comment]
When you are loading the movies? It might be first binding an empty list on rotation which would reset the scroll position.

**Comment by vtarantik** [comment]
I'm loading the movies in viewmodel's oncreate and only once per viewmodel lifetime, so hopefully this shouldn't be a problem.

**Comment by evant** [comment]
Can you look at the sample and figure out what you are doing differently?

**Comment by vtarantik** [comment]
Yes, I will, thanks for help. i'll let you know if I've found something

**Comment by vtarantik** [comment]
@evant Hi, I'm really sorry but there was a hidden call that executed the items loading, so it's not a problem of the library. Thanks a lot for all the great stuff you produce:)

**Comment by vtarantik** [comment]
Sorry, that wasn't the problem, now I'm 100% sure that the code retrieving the data is only called once but it still doesn't work, I'll try to diff it with the sample app to see what's wrong

**Comment by vtarantik** [comment]
@evant So far I've found that if you delete the recyclerview id in the sample, it stops remembering the scroll position, but adding the id doesn't solve the problem for me. So I'll keep searching.

**Comment by janbina** [comment]
@evant Hi, I also have problem with scroll position of recycler view. I figured out that problem is with setting layout manager. If layout manager is set like `app:layoutManager="@{LayoutManagers.linear()}"`, scroll position is not remembered on rotation, but if I set layout manager in code like `recycler.setLayoutManager(new LinearLayoutManager(getContext()))`, it works as expected.

**Comment by evant** [comment]
I'm removing `LayoutManagers` since recyclerview supports setting it in xml. Feel free to re-open this if you are still having issues.
