### ISSUE TITLE
Scrolling up in RecyclerView results in inconsistency with custom view

### ISSUE THREAD

**Issue by rpattabi** [evant/binding-collection-adapter#80]
I am using this library (`v1.3.0`) to databind to recyclerview. My layout for the item has custom view. Its onDraw() draws a few vector drawables to canvas.

This works fine when scrolling down, but when I scroll up quickly the custom view does not have the same state. To understand this problem, take a look at these screenshots:

# Before scrolling...
Make a note of red circle patterns. This is from custom view.
![screenshot_1493736399](https://cloud.githubusercontent.com/assets/174775/25623391/8a00ed78-2f74-11e7-94bd-e83970e979c8.png)

# After scrolling down and quickly scrolling back to top
You see that the patterns are not consistent with 'before scrolling...' state.
![screenshot_1493737532](https://cloud.githubusercontent.com/assets/174775/25624414/e9347b6e-2f76-11e7-8b3d-f2e0a6e4e461.png)

# Note
- I didn't have this problem when I used text view in place custom view. The text shown was consistent.
- The star rating that you see in the screenshots, which is not a custom view, is consistent.

# My layout
```
                <android.support.v7.widget.RecyclerView
                    android:id="@+id/drill_recyclerView"
                    android:layout_width="0dp"
                    android:layout_height="0dp"
                    android:paddingLeft="@dimen/activity_horizontal_margin"
                    tools:ignore="RtlSymmetry"

                    app:layout_constraintTop_toBottomOf="@+id/appbar"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintLeft_toLeftOf="parent"
                    app:layout_constraintRight_toRightOf="parent"

                    app:items="@{viewModel.trainingItemViewModels}"
                    app:itemView="@{viewModel.trainingItemView}"
                    app:layoutManager="@{LayoutManagers.grid(viewModel.getSpanCount())}"
                />
```

# My custom view
```
public class ExercisePatternView extends AppCompatImageView {
    private Context context;

    @Nullable
    private ExercisePattern pattern;
    @Nullable
    private List<ExercisePatternSwaramGraphic> patternGraphics;

    public ExercisePatternView(Context context) {
        super(context);
        init(context);
    }

    public ExercisePatternView(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }

    public ExercisePatternView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context);
    }

    public void setPattern(@NonNull ExercisePattern pattern) {
        this.pattern = pattern;
        invalidate();
    }

    private void init(Context context) {
        this.context = context;
    }

    @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        if (pattern == null) // can't never be, right?
            return;

        patternGraphics = pattern.draw(pxToDp(context, w), pxToDp(context, h));
    }

    @Override
    protected void onDraw(Canvas canvas) {
        if (patternGraphics == null || patternGraphics.isEmpty())
            return;

        for (ExercisePatternSwaramGraphic graphic : patternGraphics) {
            Drawable drawable = getDrawable(graphic.swaraSthayiToken.getSwaram());
            drawable.setBounds(
                    dpToPx(context, graphic.left),
                    dpToPx(context, graphic.top),
                    dpToPx(context, graphic.right),
                    dpToPx(context, graphic.bottom)
            );

            drawable.draw(canvas);
        }
    }

    private Drawable getDrawable(Swaram swaram) {
        @DrawableRes int drawableId;

        if (swaram == Sa)
            drawableId = R.drawable.ic_swaram_sa;

        else if (swaram == Ri || swaram == Ri1 || swaram == Ri2 || swaram == Ri3)
            drawableId = R.drawable.ic_swaram_ri;

        else if (swaram == Ga || swaram == Ga1 || swaram == Ga2 || swaram == Ga3)
            drawableId = R.drawable.ic_swaram_ga;

        else if (swaram == Ma || swaram == Ma1 || swaram == Ma2)
            drawableId = R.drawable.ic_swaram_ma;

        else if (swaram == Pa)
            drawableId = R.drawable.ic_swaram_pa;

        else if (swaram == Dha || swaram == Dha1 || swaram == Dha2 || swaram == Dha3)
            drawableId = R.drawable.ic_swaram_dha;

        else if (swaram == Ni || swaram == Ni1 || swaram == Ni2 || swaram == Ni3)
            drawableId = R.drawable.ic_swaram_ni;

        else
            throw new IllegalStateException();

        return ContextCompat.getDrawable(context, drawableId);
    }

}
```

Is this possibly a bug in the library (or something to do with my custom view)? Any ideas?

**Comment by evant** [comment]
My guess is it's not updating in `onBind`. I assume you are calling `setPattern()` there? I noticed that you are assigning `patternGraphics` in `onSizeChange` I don't think you can assume that will get called again when the view is recycled.

**Comment by rpattabi** [comment]
Thanks for guiding me in the right direction for this problem. 

`setPattern()` is called through data binding. This is from item layout:

```
            <com.example.ExercisePatternView
                android:id="@+id/exercise_pattern"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                android:layout_marginLeft="8dp"
                android:layout_marginRight="8dp"

                app:pattern="@{ viewModel.pattern }"
            />
```
This is the same way I had textview text and star rating imageview which worked fine, as mentioned before.

You are right that `onSizeChange` is not called when the view is recycled. I kept the setting of `patternGraphics` there since this involves creation of objects and this is needed to be done only once per view. Moving this to `onDraw` solves the problem. Obviously, not efficient.

Since setting the pattern through data binding works, doing the same for `patternGraphics` will also work. But creating it requires view's width and height.

Please let me know if you have any ideas for resolving this. In other words, what is the right approach to retain state of the view that is recycled, instead of having to do expensive work within `onDraw`?

**Comment by evant** [comment]
So you want to do the work in `setPattern()`since your data has changed. If your view is already measured you are good to go. If it's not (probably the first time you are binding to that view) you need to wait until it is.

**Comment by rpattabi** [comment]
@evant As I showed in the item layout, setPattern() is done through data binding. I believed that it would be called before view measurement. If this is true, I am only left with doing the calculations in onDraw(). I assumed that custom view need not be written keeping recycler view in mind. Now that I see it is not true.

Is this understanding correct?

**Comment by evant** [comment]
You don't have to do it in `onDraw` You just need to invalidate it when `setPattern()` is called. This is not just keeping recyclerview in mind. You'd see the same issue if you called `setPattern()` twice outside recyclerview.

**Comment by rpattabi** [comment]
It's clear. Thank you for the help!
