### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by kmalmur** [evant/binding-collection-adapter#84]
Is it possible to use some kind of data pagination with this approach?

**Comment by evant** [comment]
Since there's an official [paging lib](https://developer.android.com/topic/libraries/architecture/paging/) now, might be able to hook something up with that. Haven't tried. Might be worth an investigation and if anything needs to be added here.

**Comment by evant** [comment]
Added a new artifact with paging support. This wasn't very difficult. https://github.com/evant/binding-collection-adapter/pull/140

**Comment by BsBrabi** [comment]
@evant Is it possible to create a new beta release with paging support?

**Comment by evant** [comment]
should have been released
