### ISSUE TITLE
Issue when using OnItemBind custom implementation with a Spinner

### ISSUE THREAD

**Issue by novachevskyi** [evant/binding-collection-adapter#86]
During some time I was using v0.15 but while ago switched to v2.0.1 and faced a regression issue with a Spinner.

It seems that using `OnItemBind` custom implementation not works properly with a Spinner and for now the only workaround on a client side would be to use `ItemBinding` class instance.

Let me describe the issue itself. I have a screen which is using Spinner with a drop-down list. I've created my own generic implementation of `OnItemBind` interface which is used for all my lists and spinner's drop-down lists. After upgrading library version from v0.15 to v2.0.1 I noticed a regression issue with a Spinner drop-down list. When navigating to any screen from the screen with a Spinner and after back navigation to that screen I noticed that after clicking on the Spinner its drop-down list is going to be empty. At the same time, it still possible to click on a drop-down list item and after that drop-down list would appear.

I've spent some time on debugging and found a root cause of this issue. 

After navigating back to the screen with a Spinner application would call `BindingCollectionAdapters::setAdapter` twice because bindings are going to be executed twice in my case. 

The first time it called manually by the app screen logic. In this case, the binding adapter would set list adapter and items would be inflated. At the same time when we're using `OnItemBind` interface implementation then `variableId` and `layoutRes` values are saved to `ItemBinding.variableId` and `ItemBinding.layoutRes` fields within `BindingListViewAdapter::getItemViewType` method.

For the second time bindings would be executed automatically by `Choreographer` and library would reset `ItemBinding` instance for `BindingListViewAdapter`. And in this case, the adapter wouldn't be reset because we already have the same instance for the adapter view (`BindingCollectionAdapters::setAdapter`), so item views are not going to be re-inflated:
```
if (oldAdapter != adapter) {
    adapterView.setAdapter(adapter);
}
```
At the same time, the library would reset `ItemBinding` but wouldn't save `variableId` and `layoutRes` values to its fields. And when we're going to open Spinner then `BindingListViewAdapter::getDropDownView` would be called but `BindingListViewAdapter::getItemViewType` wouldn't and because of that `ItemBinding::onItemBind` wouldn't be executed as well. So we would end up with `ItemBinding.variableId` and `ItemBinding.layoutRes` field values are equal to 0 and because of that item view is going to be empty.

In the library, it can be fixed by adding `itemBinding.onItemBind(position, item);` call inside of `BindingListViewAdapter::getDropDownView`, but not sure if this fix would fit library design so I hope you can find any better solution.

**Comment by evant** [comment]
Not sure if this is still a problem. If it is, can you re-open the issue and create a sample project?
