### ISSUE TITLE
PageView + RecyclerView

### ISSUE THREAD

**Issue by genaku** [evant/binding-collection-adapter#87]
I can't catch how to implement PageView with some layout on pages (for example LinearLayout with TextView + RecyclerView inside). Could you please give example or inlcude it into sample app?

**Comment by soitiroseta** [comment]
first your list_layout:

<data\>
&emsp;<import type="me.tatarka.bindingcollectionadapter2.LayoutManagers" /\>
&emsp;<variable name="viewModel" type=".FragmentViewModel"/\>
</data\>

<android.support.v7.widget.RecyclerView
&emsp;android:id="@+id/list"
&emsp;android:layout_width="match_parent"
&emsp;android:layout_height="match_parent"
&emsp;app:layoutManager="@{LayoutManagers.linear()}"
&emsp;app:items="@{viewModel.items}"
&emsp;app:itemBinding="@{viewModel.itemBinding}"/>

in your root ViewModel

&emsp;val items: ObservableList<SectionModel> = ObservableArrayList()
&emsp;val itemBinding = ItemBinding.of<SectionModel> { itemBinding, position, item ->
&emsp;&emsp;itemBinding.set(BR.section, R.layout.item_paged)
&emsp;&emsp;temBinding.bindExtra(BR.sectionViewModel,
&emsp;&emsp;&emsp;&emsp;&emsp;viewModelProvider.get(SectionViewModel.key(item.id), SectionViewModel::class.java))
&emsp;&emsp;itemBinding.bindExtra(BR.section, item)
&emsp;}.layoutRes(R.layout.item_paged)

in your root item_paged

<data\>
&emsp;<variable name="section" type=".db.SectionModel"/\>
&emsp;<variable name="sectionViewModel" type=".SectionViewModel"/\>
</data\>

<android.support.v4.view.ViewPager
&emsp;android:id="@+id/pager"
&emsp;android:layout_width="match_parent"
&emsp;android:layout_height="match_parent"
&emsp;android:layout_below="@id/tab_layout"
&emsp;app:items="@{sectionViewModel.items}"
&emsp;app:itemBinding="@{sectionViewModel.itemBinding}"
&emsp;app:pageTitles="@{sectionViewModel.pageTitles}"/>

in your SectionViewModel

&emsp;val items: ObservableList<CollectionModel> = ObservableArrayList()
&emsp;val pageTitles = BindingViewPagerAdapter.PageTitles<CollectionModel> {
&emsp;&emsp;position, item -> item.title
&emsp;}

&emsp;val itemBinding = ItemBinding.of<CollectionModel> { itemBinding, position, item ->
&emsp;&emsp;itemBinding.set(BR.collection, R.layout.item_paged_list)
&emsp;&emsp;itemBinding.bindExtra(BR.collectionViewModel,
&emsp;&emsp;&emsp;&emsp;viewModelProvider.get(CollectionViewModel.key(item.id), CollectionViewModel::class.java))
&emsp;&emsp;itemBinding.bindExtra(BR.collection, item)
&emsp;}.layoutRes(R.layout.item_paged_list)

**Comment by soitiroseta** [comment]
@dakuenjery, for get  viewModelProvider i use [Dagger2](https://github.com/googlesamples/android-architecture-components/tree/master/GithubBrowserSample) with ViewModelProvider.Factory
